name:                aoc2019
version:             0.1.0.0
github:              "flo8-/aoc2019"
license:             BSD3
author:              "Florian Lloyd-Pötscher"
maintainer:          "flo@poetscher.org"
copyright:           "2019 Florian Lloyd-Pötscher"

# extra-source-files:


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Advent of Code 2019 solutions 

dependencies:
- base >= 4.7 && < 5
- containers
- split
- linear
- HUnit 
- mtl
- ansi-terminal
- vector
- search-algorithms

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
